services:
  front-end:
    build: ./frontend
    image: frontend
    container_name: frontend
    restart: always
    ports:
      - "3001:3001"
    # secrets: admi_passwd
    networks:
      - ft_transcendence

  back-end:
    build: ./backend
    image: backend
    container_name: backend
    restart: always
    ports:
      - "80:80"
    # secrets: admi_passwd
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    driver: bridge

# secrets:
#   admi_passwd:
#     file: ../secrets/admin_passwd.txt